### ISSUE TITLE
buildifier inserts spaces in optional parameters

### ISSUE THREAD

**Issue by bsubei** [bazelbuild/buildtools#805] opened 2020-03-11 18:20 UTC
Tested on version:
```
buildifier version: 2.2.1
buildifier scm revision: 22e56e7
```

Ran `buildifier` on the following file:
```
def foo(a, b, c, d=1, e=2):
    return a
```
and it incorrectly added spaces around the `=` for the optional parameters:
```
def foo(a, b, c, d = 1, e = 2):
    return a
```

**Comment by vladmos** [comment] 2020-03-11 18:22
The convention for Starlark files (unlike Python files) is to always surround binary operators, including `=` for keyword arguments, with spaces.

**Comment by bsubei** [comment] 2020-03-11 18:27
I see... The examples gave the impression that the convention was to not have spaces, so I guess the examples could be updated to follow the convention. Should I make a ticket for that?

**Comment by vladmos** [comment] 2020-03-11 18:34
What examples are you talking about? In general it's better to format all examples as buildifier would format them, so please make a ticket.

**Comment by grantwwu** [comment] 2020-03-11 18:38
The ones in the Starlark spec here https://github.com/google/skylark/blob/master/doc/spec.md#functions

**Comment by vladmos** [comment] 2020-03-11 18:47
I think it makes sense to fix the spaces there. The documentation describes the Starlark language in general (not necesarilly as a part of Bazel), but Buildifier is also supposed to work with any Starlark files.

I'm closing this ticket because it works as intended.

**Closed by vladmos** 2020-03-11 18:47 UTC

**Comment by laurentlb** [comment] 2020-03-11 21:50
Yes, examples should be updated. Thanks for pointing that out,
