### ISSUE TITLE
Lint unsorted-dict-items should not apply to //conditions:default in select

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/buildtools#487] opened 2018-12-20 15:48 UTC
It's common to format `select` expressions like this:

```
foo_library(
    name = "foo",
    srcs = select({
        "//a": ["a.foo"],
        "//z": ["z.foo"],
        "//conditions:default": [],
    }),
)
```

Currently `buildifier -lint=warn` emits a warning because the keys of the dict passed to `select` are not in lexicographic order. I think there should be an exception for the key `"//conditions:default"` when used in a `select` expression.

Many `select` expressions need to have a `"//conditions:default"` case, since Bazel will report an error if no case matches. I'd argue that it's more readable for the default case to be at the bottom of the `select`, instead of between `a` and `z`, especially when the default case is empty. Programmers are used to the default case being at the bottom of `switch` statements in other languages, so I think this is a natural place for it.  I don't think this is mentioned explicitly in a style guide, but in a brief search of build files within Google, I couldn't find any cases where `//conditions:default` is not at the bottom of a `select`; there may be some cases out there, but the bottom is by far the most common location.

**Comment by jwnimmer-tri** [comment] 2018-12-20 15:54
Is this a duplicate of #480 (just fixed a few hours ago)?

**Comment by vladmos** [comment] 2018-12-20 15:55
Most probably yes. I'm closing the issue, please reopen if you're still experiencing the issue.

**Closed by vladmos** 2018-12-20 15:55 UTC

**Comment by jayconrod** [comment] 2018-12-20 15:59
Yes, looks like a dup. Thanks for fixing already, sorry for the noise.
