### ISSUE TITLE
unsorted-dict-items & out-of-order-load not autofixed by buildifier?

### ISSUE THREAD

**Issue by smukherj1** [bazelbuild/buildtools#575] opened 2019-03-07 16:57 UTC
I'm using buildifier: 0.22.0

When I run buildifier on my code, it doesn't change the load order or the dict items. After the buildifier autoformat, when I run buildifier with --lint=warn and these warnings turned on, it complains about them. The README suggests these issues should be autofixed.

To reproduce:
Download bazelbuild/bazel-toolchains at commit 09c26bd109b44be2faecab77378a001d9bed3886

Run buildifier 0.22.0 on configs/dependency-tracking/ubuntu1604.bzl configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/cc_toolchain_config.bzl

run buildifier with --lint=warn --warnings=unsorted-dict-items,out-of-order-load configs/dependency-tracking/ubuntu1604.bzl  configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/cc_toolchain_config.bzl

You should see
```
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/BUILD:49: unsorted-dict-items: Dictionary items are out of their lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/BUILD:50: unsorted-dict-items: Dictionary items are out of their lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/BUILD:51: unsorted-dict-items: Dictionary items are out of their lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/BUILD:125: out-of-order-load: Load statement is out of its lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/cc_toolchain_config.bzl:31: out-of-order-load: Load statement is out of its lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/cc_toolchain_config.bzl:1735: unsorted-dict-items: Dictionary items are out of their lexicographical order.
```

**Comment by smukherj1** [comment] 2019-03-07 17:12
Actually ignore the issue in "cc_toolchain_config.bzl" because it seems I wasn't running buildifier on bzl files. But the BUILD file seems to be affected

**Comment by smukherj1** [comment] 2019-03-07 17:21
Ok I ran buildifier 0.22.0 on the bzl files see (https://github.com/bazelbuild/bazel-toolchains/pull/351) and it didn't fix the load order issue.

**Comment by vladmos** [comment] 2019-03-08 16:39
Do you specify the `--warnings=` parameter when call buildifier with `--lint=fix`? These two categories (unsorted-dict-items, out-of-order-load) are disabled by default because some users complained the fixes weren't helpful for them (although they were technically correct), you need to provide either `--warnings=all`, or `--warnings=+unsorted-dict-items,+out-of-order-load`, or `--warnings=unsorted-dict-items,out-of-order-load,<some other categories>` to enable them.

**Comment by smukherj1** [comment] 2019-03-08 19:01
buildifier 0.22.0 seems to be making breaking changes when I use `--lint=fix --warnings=all`.
 Attached a BUILD file that reproduces the issue. You'll see this BUILD file has a load statement that imports the symbol `cc_toolchain_config` on line 19. When I run
`buildifier --lint=fix --warnings=all BUILD`

on this file. This load statement is moved to nearly the end of the file *after* the various invocations of `cc_toolchain_config`. As a result, an attempt to build the `cc_toolchain_config` targets fail.

**Comment by vladmos** [comment] 2019-03-11 15:53
Thanks for reporting, I've reproduced the issue.

Could you please also confirm that the original issue is fixed by providing `--warnings=all`?

**Comment by smukherj1** [comment] 2019-03-11 15:55
Yes the load statement and dict item sorting seem to be running with --warnings=all

**Comment by vladmos** [comment] 2019-03-11 16:04
Alternatively I can only sort chunks of consequent load statements and remove the restriction for the file types it's applied to.

**Comment by laurentlb** [comment] 2019-03-11 16:55
Eventually, we should have all load statements at the top of BUILD files.

**Comment by vladmos** [comment] 2019-03-11 18:17
With my fix it'll sort any consequent chunk of load statements in any file, including WORKSPACE files (where moving all load statements to the top is not always possible). If all load statements are already at the top, they'll all be rearranged by this fix.

**Closed** 2019-03-18 14:59 UTC
