### ISSUE TITLE
buildozer: moves comment to the wrong place

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/buildtools#71] opened 2017-03-22 15:24 UTC
old BUILD file:
go_library(
    name = "loader",
    srcs = ["loader.go"],
    deps = [":loader-impl"],  # keep
)

new BUILD file after 
`buildozer 'add deps //public' :loader` :
go_library(
    name = "loader",
    srcs = ["loader.go"],
    cgo = 1,
    deps = [
        ":loader-impl",
        "//public",  # keep
    ],
)

**Comment by forumulator** [comment] 2017-03-25 04:22
Working on this issue, and also adding Documentation(README.md and the `Usage()` function) in a separate branch.

**Comment by forumulator** [comment] 2017-03-31 09:53
@pmbethe09 Can't reproduce this, it works as expected for me. Input:
```
go_library(
name = "loader",
srcs = ["loader.go"],
deps = [":loader-impl"], # keep
)
```
Output after : `buildozer --stdout 'add deps //public' :loader` :
```
go_library(
    name = "loader",
    srcs = ["loader.go"],
    deps = [
        ":loader-impl",
        "//public",
    ],  # keep
)
```

Maybe it's already been resolved?

**Comment by pmbethe09** [comment] 2017-03-31 19:13
Shouldn't this be associated with ":loader-impl" since it is a single element list?

**Comment by laurentlb** [comment] 2017-06-08 11:11
Behavior reported by forumulator is correct, so I'm closing the issue.

The original bug was caused by buildifier (it moved the comment inside the list). I think it has been fixed.

**Closed by laurentlb** 2017-06-08 11:11 UTC
