### ISSUE TITLE
mode=fix breaks tuple assigment

### ISSUE THREAD

**Issue by nicolov** [bazelbuild/buildtools#227] opened 2018-03-07 01:11 UTC
Minimal repro:

```
echo 'a, b = [1, 2]' | buildifier -mode=fix
```

Result:

```
a

b = [
    1,
    2,
]
```

**Comment by pmbethe09** [comment] 2018-03-07 13:21
Well tuples are not allowed in BUILD syntax, so this is the *correct* formatting.

In skylark I am not sure if tuples are allowed on the LHS.
https://docs.bazel.build/versions/master/skylark/language.html

Is not clear on that.

@laurentlb

**Comment by nicolov** [comment] 2018-03-07 16:38
I had the same issue when running against a .bzl file, where tuple assignment otherwise seems to work.

I worked around this by wrapping the LHS in `()`

**Comment by laurentlb** [comment] 2018-03-07 16:49
Tuples are allowed in BUILD files.
@vladmos is fixing this bug

**Comment by vladmos** [comment] 2018-03-07 17:06
This is a duplicate of #199. #228 addresses this issue.

By the way, given that you don't get a syntax error on your repro, you probably don't use the latest version of Buildifier (which also doesn't support tuple assignments). Please update to master once #228 has been merged.

**Closed by vladmos** 2018-03-07 17:06 UTC

**Comment by pmbethe09** [comment] 2018-03-07 18:36
Ah nice -- somehow I never knew about tuples in BUILD.

@vladmos -- we should cut a new binary drop when #228 is in.  I can do it tomorrow probably.
